### ISSUE TITLE
Throwing error on grunt build

### ISSUE THREAD

**Issue by vectorderivative** [jamesharrington/angular-static-include#4]
bower angular-static-include#~2.0.1                   mismatch Version declared in the json (1.0.0) is different than the resolved one (2.0.1)

Pretty straight forward, the version in the json file should be updated along the actual version.

**Comment by codenamezjames** [comment]
I'm confused i don't require any version of angular in the bower json could you elaborate.

**Comment by vectorderivative** [comment]
Yeah, sorry.
The bower.json needs the version property to be the same as the corresponding release.
Right now, every version on the repository has a bower.json with the version set to 1.0
This mismatch makes grunt to throw that error.

**Comment by codenamezjames** [comment]
Ahh thanks i updated the version. To 2.0.1 :-)
